2017/08/15 14:18:49 [error] 6#6: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/var/www/symfony/var/cache/prod)
' in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:676
Stack trace:
#0 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(576): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(119): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(168): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(19): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 676" while reading response header from upstream, client: 172.26.0.1, server: symfony.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.3:9001", host: "localhost"
2017/08/15 14:18:49 [error] 6#6: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/var/www/symfony/var/cache/prod)
' in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:676
Stack trace:
#0 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(576): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(119): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(168): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(19): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 676" while reading response header from upstream, client: 172.26.0.1, server: symfony.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.3:9001", host: "localhost"
2017/08/15 14:18:50 [error] 6#6: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/var/www/symfony/var/cache/prod)
' in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:676
Stack trace:
#0 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(576): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(119): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(168): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(19): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 676" while reading response header from upstream, client: 172.26.0.1, server: symfony.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.3:9001", host: "localhost"
2017/08/15 14:18:50 [error] 6#6: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/var/www/symfony/var/cache/prod)
' in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:676
Stack trace:
#0 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(576): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(119): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(168): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(19): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 676" while reading response header from upstream, client: 172.26.0.1, server: symfony.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.3:9001", host: "localhost"
2017/08/15 14:19:09 [error] 6#6: *7 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/var/www/symfony/var/cache/prod)
' in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:676
Stack trace:
#0 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(576): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(119): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(168): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(19): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 676" while reading response header from upstream, client: 172.26.0.1, server: symfony.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.3:9001", host: "localhost"
2017/08/15 14:19:09 [error] 6#6: *7 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/var/www/symfony/var/cache/prod)
' in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:676
Stack trace:
#0 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(576): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(119): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(168): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(19): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 676" while reading response header from upstream, client: 172.26.0.1, server: symfony.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.3:9001", host: "localhost"
2017/08/16 09:57:41 [error] 11#11: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/var/www/symfony/var/cache/prod)
' in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:676
Stack trace:
#0 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(576): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(119): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(168): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(19): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 676" while reading response header from upstream, client: 172.26.0.1, server: symfony.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.3:9001", host: "localhost"
2017/08/16 09:58:07 [error] 11#11: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/var/www/symfony/var/cache/prod)
' in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:676
Stack trace:
#0 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(576): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(119): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(168): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(19): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 676" while reading response header from upstream, client: 172.26.0.1, server: symfony.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.3:9001", host: "localhost"
2017/08/16 09:59:26 [error] 11#11: *7 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/var/www/symfony/var/cache/prod)
' in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:676
Stack trace:
#0 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(576): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(119): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(168): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(19): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 676" while reading response header from upstream, client: 172.26.0.1, server: symfony.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.3:9001", host: "localhost"
2017/08/16 09:59:27 [error] 11#11: *7 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/var/www/symfony/var/cache/prod)
' in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:676
Stack trace:
#0 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(576): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(119): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(168): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(19): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 676" while reading response header from upstream, client: 172.26.0.1, server: symfony.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.3:9001", host: "localhost"
2017/08/16 10:00:20 [error] 11#11: *11 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/var/logs)
' in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:679
Stack trace:
#0 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(576): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(119): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(168): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(19): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/symfony/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 679" while reading response header from upstream, client: 172.26.0.1, server: symfony.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.3:9001", host: "localhost"
2017/08/16 11:40:17 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: PHP Warning:  require(/var/www/symfony/web/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/symfony/web/app.php on line 5
PHP message: PHP Fatal error:  require(): Failed opening required '/var/www/symfony/web/../vendor/autoload.php' (include_path='.:/usr/share/pear') in /var/www/symfony/web/app.php on line 5" while reading response header from upstream, client: 172.26.0.1, server: symfony.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.4:9001", host: "localhost"
2017/08/16 11:40:17 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: PHP Warning:  require(/var/www/symfony/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/symfony/web/app.php on line 5
PHP message: PHP Fatal error:  require(): Failed opening required '/var/www/symfony/web/../vendor/autoload.php' (include_path='.:/usr/share/pear') in /var/www/symfony/web/app.php on line 5" while reading response header from upstream, client: 172.26.0.1, server: symfony.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.4:9001", host: "localhost"
2017/08/16 11:40:30 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: PHP Warning:  require(/var/www/symfony/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/symfony/web/app.php on line 5
PHP message: PHP Fatal error:  require(): Failed opening required '/var/www/symfony/web/../vendor/autoload.php' (include_path='.:/usr/share/pear') in /var/www/symfony/web/app.php on line 5" while reading response header from upstream, client: 172.26.0.1, server: symfony.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.4:9001", host: "localhost"
2017/08/16 11:40:30 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: PHP Warning:  require(/var/www/symfony/web/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/symfony/web/app.php on line 5
PHP message: PHP Fatal error:  require(): Failed opening required '/var/www/symfony/web/../vendor/autoload.php' (include_path='.:/usr/share/pear') in /var/www/symfony/web/app.php on line 5" while reading response header from upstream, client: 172.26.0.1, server: symfony.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.4:9001", host: "localhost"
